### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ciphermagic** [jrainlau/jrainlau.github.io#11]
是不是提交了一个issue，博客页面就会自动加载？
由于issue谁都可以提，能不能把博文的markdown放到仓库中呢，有没有api把仓库中的博文加载出来？

**Comment by jrainlau** [comment]
可以啊，你看看api文档。
至于你说的issue谁都可以提，我在博客里面设置了过滤，只有我自己的才会展示出来，所以不用担心

**Comment by GeSnowBoy** [comment]
我也写了一个 不过是一个半成品,没有时间弄了
访问地址是 : https://gesnowboy.github.io/blog/#?owner=jrainlau&blog=jrainlau.github.io
我的可以访问别人的issues生成博客,只需要加上owner:用户名 和  blog:仓库名   比如:
https://gesnowboy.github.io/blog/#?owner=jrainlau&blog=jrainlau.github.io

**Comment by phymo** [comment]
为什么我看到的是报错401
是不是需要用github 登陆？
login with with写错了

**Comment by GeSnowBoy** [comment]
他的需要授权登录下  可以试试我的

**Comment by jrainlau** [comment]
@phymo 刚优化了一波

**Comment by Liugq5713** [comment]
> 他的需要授权登录下 可以试试我的

你这个有点帅啊
